defmodule KinoShotDs.TptpParser do
  @moduledoc """
  A Smart Cell that can parse either a raw TH0 formula (with an optional
  context) or a full TH0 problem file.
  """

  alias ShotDs.{Parser, Tptp}
  alias ShotDs.Data.Context

  use Kino.JS, assets_path: "lib/assets/tptp_parser"
  use Kino.JS.Live
  use Kino.SmartCell, name: "TPTP Parser"

  @dialyzer nowarn_function: [run_parse: 1]

  @default_formula "![X : $o]: X => X"
  @default_problem "thf(test, conjecture, $true => $true)."
  @default_context ""

  @impl true
  def init(attrs, ctx) do
    state = %{
      mode: Map.get(attrs, "mode", "problem"),
      problem_str: Map.get(attrs, "problem_str", @default_problem),
      formula_str: Map.get(attrs, "formula_str", @default_formula),
      context_str: Map.get(attrs, "context_str", @default_context),
      var_name: Map.get(attrs, "var_name", "parsed_formula_or_problem"),
      theme: Map.get(attrs, "theme", "Dracula")
    }

    {:ok, assign(ctx, state)}
  end

  @impl true
  def handle_connect(ctx) do
    {:ok, ctx.assigns, ctx}
  end

  @impl true
  def handle_info({:preview_result, {:ok, result}}, ctx) do
    broadcast_event(ctx, "preview", %{"text" => inspect(result)})
    {:noreply, ctx}
  end

  @impl true
  def handle_info({:preview_result, {:error, reason}}, ctx) do
    broadcast_event(ctx, "preview_error", %{"message" => inspect(reason)})
    {:noreply, ctx}
  end

  @impl true
  def handle_event("update", params, ctx) do
    allowed = ~w(mode problem_str formula_str context_str var_name theme)

    atom_params =
      for {k, v} <- params, k in allowed, into: %{} do
        {String.to_existing_atom(k), v}
      end

    {:noreply, assign(ctx, Map.merge(ctx.assigns, atom_params))}
  end

  @impl true
  def handle_event("quick_eval_btn", %{"action" => "parse"}, ctx) do
    parent = self()
    assigns = ctx.assigns

    Task.start(fn ->
      res = run_parse(assigns)
      send(parent, {:preview_result, res})
    end)

    {:noreply, ctx}
  end

  # --- Parse dispatch ---

  defp run_parse(%{mode: "problem", problem_str: prob}) do
    Tptp.parse_tptp_string(prob)
  end

  defp run_parse(%{mode: "formula", formula_str: formula, context_str: ctx_str}) do
    with {:ok, context} <- parse_ctx(ctx_str) do
      Parser.parse(formula, context)
    end
  end

  defp parse_ctx(str) when str in ["", nil], do: {:ok, Context.new()}
  defp parse_ctx(str), do: Parser.parse_context(str)

  @impl true
  def to_attrs(ctx) do
    Map.take(ctx.assigns, [
      :mode,
      :problem_str,
      :formula_str,
      :context_str,
      :var_name,
      :theme
    ])
  end

  @impl true
  def to_source(%{mode: "problem", problem_str: prob, var_name: var}) do
    var_ast = Macro.var(String.to_atom(var), nil)

    quote do
      # Generated by TptpParser Smart Cell
      problem = unquote(prob)

      unquote(var_ast) =
        case ShotDs.Tptp.parse_tptp_string(problem) do
          {:ok, parsed} ->
            parsed

          {:error, reason} ->
            raise "Error: #{inspect(reason)}"
        end

      :ok
    end
    |> Kino.SmartCell.quoted_to_string()
  end

  def to_source(%{mode: "formula", formula_str: formula, context_str: ctx_str, var_name: var}) do
    var_ast = Macro.var(String.to_atom(var), nil)

    quoted =
      if String.trim(ctx_str || "") == "" do
        quote do
          # Generated by TptpParser Smart Cell
          formula = unquote(formula)

          unquote(var_ast) =
            case ShotDs.Parser.parse(formula) do
              {:ok, term_id} ->
                term_id

              {:error, reason} ->
                raise "Error: #{inspect(reason)}"
            end

          :ok
        end
      else
        quote do
          # Generated by TptpParser Smart Cell
          formula = unquote(formula)
          context = ShotDs.Parser.parse_context!(unquote(ctx_str))

          unquote(var_ast) =
            case ShotDs.Parser.parse(formula, context) do
              {:ok, term_id} ->
                term_id

              {:error, reason} ->
                raise "Error: #{inspect(reason)}"
            end

          :ok
        end
      end

    Kino.SmartCell.quoted_to_string(quoted)
  end
end
